FROM busybox
ADD go/bin/myblog /app/myblog 
ADD go/src/myblog/views /app/views
ADD go/src/myblog/conf /app/conf
ADD go/src/myblog/static /app/static

WORKDIR /app
VOLUME /app/data
EXPOSE 8080
CMD myblog