FROM busybox
MAINTAINER <284077318@qq.com> 
ADD go/bin/myblog /usr/bin/myblog
#/app/myblog 
# ADD go/src/myblog/views /app/views
# ADD go/src/myblog/conf /app/conf
# ADD go/src/myblog/static /app/static

# WORKDIR /app
# VOLUME /app/data
EXPOSE 8080
CMD /usr/bin/myblog