FROM busybox
MAINTAINER <284077318@qq.com> 
ADD go/bin/myblog /app/myblog
#/usr/bin/myblog
ADD go/src/myblog/views /app/views
ADD go/src/myblog/conf /app/conf
ADD go/src/myblog/static /app/static

WORKDIR /app
VOLUME /app/data
EXPOSE 8080
CMD myblog